using System;
using System.Collections.Generic;

namespace MdExplorer.Abstractions.Services
{
    /// <summary>
    /// Full-text content index over the project's markdown files.
    /// Backed by a side-car SQLite database (MdEngineFts_{hash}.db, FTS5 trigram)
    /// kept next to the engine database. The index is rebuilt by the indexing
    /// pipeline on every project open and kept fresh by the FileSystemWatcher,
    /// so it can always be regenerated by reopening the project.
    /// </summary>
    public interface IMarkdownFtsService
    {
        /// <summary>Atomically replaces the whole index for a project.</summary>
        void RebuildIndex(string projectPath, IReadOnlyCollection<MarkdownFtsEntry> entries);

        /// <summary>Inserts or replaces the row for a single file (keyed by full path).</summary>
        void UpsertFile(string projectPath, Guid markdownFileId, string fullPath, string fileName, string content);

        /// <summary>Removes the row for a file. Safe to call when no row exists.</summary>
        void DeleteFileByPath(string projectPath, string fullPath);

        /// <summary>
        /// Substring search (trigram). Terms shorter than 3 characters return an
        /// empty list (physical limit of the trigram tokenizer). Snippets are
        /// HTML-escaped with &lt;mark&gt;…&lt;/mark&gt; around matches.
        /// </summary>
        List<ContentSearchResult> SearchContent(string projectPath, string searchTerm, int maxResults = 50);
    }

    public class MarkdownFtsEntry
    {
        public Guid MarkdownFileId { get; set; }
        public string Path { get; set; }
        public string FileName { get; set; }
        public string Content { get; set; }
    }
}
