import { Injectable, Injector } from '@angular/core';
import * as signalR from "@microsoft/signalr";
import { GITService } from '../../git/services/gitservice.service';
import { ConnectionLostProvider } from '../../signalR/dialogs/connection-lost/connection-lost.provider';
import { ParsingProjectProvider } from '../../signalR/dialogs/parsing-project/parsing-project.provider';
import { PlantumlWorkingProvider } from '../../signalR/dialogs/plantuml-working/plantuml-working.provider';
import { connect } from 'net';
import { OpeningApplicationProvider } from '../dialogs/opening-application/opening-application.provider';
import { Subject, ReplaySubject } from 'rxjs';

interface linkSignalREvent_Component {
  key: string
  object: any;
  callback: (data: any, objectThis: any) => any
}

@Injectable({
  providedIn: 'root'
})
export class MdServerMessagesService {

  linkEventCompArray: linkSignalREvent_Component[];
  public connectionId: string;

  /** Emits the connectionId once available (and on every reconnection). ReplaySubject(1) so late subscribers get the last value immediately. */
  public connectionId$ = new ReplaySubject<string>(1);

  // Observable for Git branch switch events
  public gitBranchSwitched$ = new Subject<{ fileCount: number, message: string }>();

  // Observable for Git pull refresh events
  public gitPullRefreshed$ = new Subject<{ fileCount: number, message: string }>();

  // Observable for RAG indexing progress events
  public ragIndexingProgress$ = new Subject<{ status: string, processed: number, total: number, message: string }>();

  // Observable for App Store publish progress (backend → Nexus upload)
  public publishProgress$ = new Subject<{ appId: string, percent: number, phase: string }>();

  // Observable for the Mark folder-summarizer job progress (MarkActionsController)
  public markFolderProgress$ = new Subject<any>();

  // Observable for Screenshot Annotation Wizard (from iframe Ctrl+V)
  public screenshotAnnotationRequest$ = new Subject<{
    success: boolean,
    imageBase64?: string,
    mimeType?: string,
    documentPath?: string,
    errorMessage?: string,
    platformHint?: string
  }>();

  // Observable streams for runnable fenced code blocks (MdExecutionController)
  public executionOutput$ = new Subject<{ blockId: string, stream: string, chunk: string }>();
  public executionCompleted$ = new Subject<{ blockId: string, exitCode: number, durationMs: number, timedOut: boolean }>();
  public executionError$ = new Subject<{ blockId: string, message: string }>();

  constructor(
    private parsingProjectProvider: ParsingProjectProvider,
    private plantumlWorkingProvider: PlantumlWorkingProvider,
    private connectionLostProvider: ConnectionLostProvider,
    private openingApplicationProvider: OpeningApplicationProvider,
    private gitService: GITService,
    private injector: Injector) {
    this.startConnection();
    console.log('MonitorMDService constructor');
    this.linkEventCompArray = [];

  }

  private hubConnection: signalR.HubConnection
  private rule1IsRegistered: any;
  private connectionIsLost: boolean = false;
  private consoleIsClosed: boolean = false;
  

  public startConnection = () => {
    if (this.hubConnection == null) {
      this.hubConnection = new signalR.HubConnectionBuilder()
        .withUrl('../signalr/monitormd')
        .build();
      this.hubConnection.on('markdownfileisprocessed', (data) => {
        this.processCallBack(data, 'markdownfileisprocessed');
      });
      this.hubConnection.on('yamlAutoGenerated', (data) => {
        this.processCallBack(data, 'yamlAutoGenerated');
      });
      this.hubConnection.on('documentNavigated', (data) => {
        this.processCallBack(data, 'documentNavigated');
      });
      // parsingProjectStart/Stop NON aprono più la MatDialog modale "Building knowledge"
      // (era il blocker UX: backdrop modale → utente inibito per tutta l'indicizzazione).
      // Dopo il refactor del 2026-05-23 la pipeline è davvero async (Task.Yield in
      // IndexingPipelineService.RunAsync) e mostriamo il progresso con una snackbar
      // custom (IndexingProgressSnackComponent) montata da md-tree.component.ts via
      // addParsingProjectStartListener (sotto).
      this.hubConnection.on('openingApplication', (data) => {
        this.openingApplicationProvider.show(data);
      });
      this.hubConnection.on('plantumlWorkStart', (data) => {
        this.plantumlWorkingProvider.show(data);
      });
      this.hubConnection.on('plantumlWorkStop', (data) => {
        this.plantumlWorkingProvider.hide(data);
      });
      this.hubConnection.on('indexingFolder', (folder) => {
        this.parsingProjectProvider.folder$.next(folder);
      });

      // Git branch switch event (client-specific, from ModernGitController)
      this.hubConnection.on('gitBranchSwitched', (data) => {
        console.log('✅ SignalR event received: gitBranchSwitched', data);
        this.gitBranchSwitched$.next(data);
      });

      // Git pull refresh event (from ModernGitToolbarController)
      this.hubConnection.on('gitPullRefreshed', (data) => {
        console.log('✅ SignalR event received: gitPullRefreshed', data);
        this.gitPullRefreshed$.next(data);
      });

      // Screenshot Annotation Wizard event (from iframe Ctrl+V via backend clipboard read)
      this.hubConnection.on('openScreenshotAnnotationWizard', (data) => {
        console.log('📷 SignalR event received: openScreenshotAnnotationWizard', data);
        this.screenshotAnnotationRequest$.next(data);
      });

      // RAG indexing progress event (from RagController background task)
      this.hubConnection.on('ragIndexingProgress', (data) => {
        this.ragIndexingProgress$.next(data);
      });

      // App Store publish progress (backend → Nexus upload)
      this.hubConnection.on('publishProgress', (data) => {
        this.publishProgress$.next(data);
      });

      // Mark folder-summarizer job progress
      this.hubConnection.on('markFolderProgress', (data) => {
        this.markFolderProgress$.next(data);
      });

      // Runnable fenced code blocks — streaming output from MdExecutionController
      this.hubConnection.on('execution.output', (data) => {
        this.executionOutput$.next(data);
      });
      this.hubConnection.on('execution.completed', (data) => {
        this.executionCompleted$.next(data);
      });
      this.hubConnection.on('execution.error', (data) => {
        this.executionError$.next(data);
      });

      this.hubConnection.on('consoleClosed', (data) => {
        console.log('consoleClosed');
        this.consoleIsClosed = true;
        this.connectionLostProvider.showConsoleClosed();
      });
      this.hubConnection.onclose((data) => {
        console.warn('🔴 [DIAG] SignalR CLOSED at:', new Date().toISOString(), 'consoleIsClosed:', this.consoleIsClosed);
        if (!this.consoleIsClosed) {
          this.connectionLostProvider.show(this);
          this.connectionIsLost = true;
        }
      });

    }

    if (this.hubConnection.state == "Disconnected") {
      const wasReconnection = this.connectionIsLost; // Capture before reset
      this.hubConnection
        .start()
        .then(() => {
          console.log('Connection started');
          console.warn('🔴 [DIAG] SignalR STARTED. wasReconnection:', wasReconnection, 'at:', new Date().toISOString());
          this.connectionIsLost = false;
          this.getCurrentConnectionId(this, wasReconnection);
        }

        )
        .catch(err => {
          console.log('Error while starting connection: ' + err);
        }
        );
    }

    

  }




  public addRefactoringFileEvent(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('refactoringFileEvent', (data) => {
      callback(data, objectThis);
    });
  }


  public addMarkdownFileListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('markdownfileischanged', (data) => {
      // Modern Git service will automatically update via polling - no manual refresh needed
      callback(data, objectThis);
      console.log('markdownfileischanged');
    });
  }

  private processCallBack(data: any, signalREvent: string) {
    this.linkEventCompArray.forEach(_ => {
      if (_.key == signalREvent) {
        _.callback(data, _.object);
      }
    })
  }



  public addMdProcessedListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    let check = this.linkEventCompArray.find(_ =>
      _.key == 'markdownfileisprocessed' && _.object.constructor.name === objectThis.constructor.name);
    if (check == undefined) {
      this.linkEventCompArray.push({ key: 'markdownfileisprocessed', object: objectThis, callback: callback });
    }
  }

  public addMdRule1Listener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    // giusto per evitare di effettuare l'instanziazione un centinaio di volte l'evento
    console.log('addMdRule1Listener');
    if (this.rule1IsRegistered == undefined) {
      this.rule1IsRegistered = objectThis;
      this.hubConnection.on('markdownbreakrule1', (data) => {
        callback(data, objectThis);
      });
    }
  }

  public addPdfIsReadyListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('pdfisready', (data) => {
      callback(data, objectThis);
    });
  }

  public addYamlAutoGeneratedListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    let check = this.linkEventCompArray.find(_ =>
      _.key == 'yamlAutoGenerated' && _.object.constructor.name === objectThis.constructor.name);
    if (check == undefined) {
      this.linkEventCompArray.push({ key: 'yamlAutoGenerated', object: objectThis, callback: callback });
    }
  }

  public addDocumentNavigatedListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    let check = this.linkEventCompArray.find(_ =>
      _.key == 'documentNavigated' && _.object.constructor.name === objectThis.constructor.name);
    if (check == undefined) {
      this.linkEventCompArray.push({ key: 'documentNavigated', object: objectThis, callback: callback });
    }
  }

  // Listener per forzare l'aggiornamento di file rinominati (Rule #1 fix)
  private rule1ForceUpdateRegistered: any;
  public addRule1ForceUpdateListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    console.log('addRule1ForceUpdateListener');
    if (this.rule1ForceUpdateRegistered == undefined) {
      this.rule1ForceUpdateRegistered = objectThis;
      // Non abbiamo bisogno di un evento SignalR reale, useremo questo per il pattern locale
    }
  }
  
  // Metodo per triggerare l'evento di force update localmente
  public triggerRule1ForceUpdate(filePath: string): void {
    if (this.rule1ForceUpdateRegistered?.handleRule1ForceUpdate) {
      this.rule1ForceUpdateRegistered.handleRule1ForceUpdate(filePath);
    }
  }

  public addFileIndexedListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('fileIndexed', (data) => {
      callback(data, objectThis);
    });
  }

  public addFolderIndexingStartListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('folderIndexingStart', (data) => {
      callback(data, objectThis);
    });
  }

  public addFolderIndexingCompleteListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('folderIndexingComplete', (data) => {
      callback(data, objectThis);
    });
  }

  public addParsingProjectStartListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('parsingProjectStart', (data) => {
      callback(data, objectThis);
    });
  }

  public addMarkdownFileCreatedListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('markdownFileCreated', (data) => {
      console.log('📄 [SignalR] Evento markdownFileCreated ricevuto:');
      console.log('📄 [SignalR] Data ricevuta:', JSON.stringify(data, null, 2));
      console.log('📄 [SignalR] Nome file:', data.name);
      console.log('📄 [SignalR] Path completo:', data.fullPath);
      callback(data, objectThis);
    });
  }

  public addMarkdownFileDeletedListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('markdownFileDeleted', (data) => {
      console.log('🗑️ [SignalR] Evento markdownFileDeleted ricevuto:');
      console.log('🗑️ [SignalR] Data ricevuta:', JSON.stringify(data, null, 2));
      console.log('🗑️ [SignalR] Nome file:', data.name);
      console.log('🗑️ [SignalR] Path completo:', data.fullPath);
      callback(data, objectThis);
    });
  }

  public addParsingProjectStopListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('parsingProjectStop', (data) => {
      callback(data, objectThis);
    });
  }

  /**
   * "Building knowledge" progress event — emesso da IndexingPipelineService
   * dopo ogni cartella nella fase ParseLinks. Payload:
   *   { processed: number, total: number, percent: 0..100 }
   * Pilotato verso IndexingProgressService dalla snackbar custom in md-tree.
   */
  public addKnowledgeProgressListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('knowledgeProgress', (data) => {
      callback(data, objectThis);
    });
  }

  public addConnectionIdListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('getconnectionid', (data) => {
      callback(data, objectThis);
    });
  }

  public getConnectionId(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.invoke('GetConnectionId')
      .then(function (connectionId) {        
        objectThis.connectionId = connectionId;
        callback(connectionId, objectThis);
      });
  }

  public getCurrentConnectionId(objectThis: MdServerMessagesService, isReconnection: boolean = false): void {
    this.hubConnection.invoke('GetConnectionId')
      .then(function (connectionId) {
        objectThis.connectionId = connectionId;
        objectThis.connectionId$.next(connectionId);

        // Notify Electron that connectionId is ready (for URL handler feature)
        if ((window as any).electronAPI?.notifyConnectionIdReady) {
          console.log('[SignalR] Notifying Electron of connectionId:', connectionId);
          (window as any).electronAPI.notifyConnectionIdReady(connectionId);
        }

        // If this was a reconnection, re-register the current project with the new connectionId
        // This is necessary because when SignalR disconnects, the backend cleans up
        // FileSystemWatcher and DatabaseContext for the old connectionId
        if (isReconnection) {
          console.log('[SignalR] Reconnection detected, re-registering project...');
          objectThis.reregisterCurrentProject();
        }
      });
  }

  private reregisterCurrentProject(): void {
    // Use dynamic import to avoid circular dependency issues
    import('../../md-explorer/services/projects.service').then(module => {
      const projectsService = this.injector.get(module.ProjectsService);
      projectsService.reregisterCurrentProject();
    }).catch(err => {
      console.error('[SignalR] Failed to re-register project:', err);
    });
  }

  // TOC Generation listeners
  public addTocGenerationProgressListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('TocGenerationProgress', (data) => {
      console.log('[SignalR] TOC Generation Progress:', data);
      callback(data, objectThis);
    });
  }

  public addTocGenerationCompleteListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('TocGenerationComplete', (data) => {
      console.log('[SignalR] TOC Generation Complete:', data);
      callback(data, objectThis);
    });
  }

  // AI File Operation listener
  public addAiFileOperationListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('aiFileOperation', (data) => {
      console.log('[SignalR] AI File Operation:', data);
      callback(data, objectThis);
    });
  }

  // URL Handler listeners
  public addUrlHandlerOpenDocumentListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('urlHandlerOpenDocument', (data) => {
      console.log('[SignalR] URL Handler Open Document:', data);
      callback(data, objectThis);
    });
  }

  public addUrlHandlerOpenConfigProjectDialogListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    // Listen for new configproject event
    this.hubConnection.on('urlHandlerOpenConfigProjectDialog', (data) => {
      console.log('[SignalR] URL Handler Open ConfigProject Dialog:', data);
      callback(data, objectThis);
    });
    // Also listen for legacy clone event for backward compatibility
    this.hubConnection.on('urlHandlerOpenCloneDialog', (data) => {
      console.log('[SignalR] URL Handler Open Clone Dialog (legacy):', data);
      callback(data, objectThis);
    });
  }

  public addUrlHandlerErrorListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('urlHandlerError', (data) => {
      console.log('[SignalR] URL Handler Error:', data);
      callback(data, objectThis);
    });
  }

  // Bulk Export listeners
  public addBulkExportProgressListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('BulkExportProgress', (data) => {
      callback(data, objectThis);
    });
  }

  public addBulkExportCompleteListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('BulkExportComplete', (data) => {
      callback(data, objectThis);
    });
  }

  public addFolderCreatedListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('folderCreated', (data) => {
      console.log('📁 [SignalR] Evento folderCreated ricevuto:', data?.fullPath || data?.FullPath);
      callback(data, objectThis);
    });
  }

  public addFolderDeletedListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('folderDeleted', (data) => {
      console.log('🗑️ [SignalR] Evento folderDeleted ricevuto:', data?.fullPath || data?.FullPath);
      callback(data, objectThis);
    });
  }

  public addFolderRenamedListener(callback: (data: any, objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('folderRenamed', (data) => {
      console.log('✏️ [SignalR] Evento folderRenamed ricevuto:', data?.oldFullPath || data?.OldFullPath, '→', data?.fullPath || data?.FullPath);
      callback(data, objectThis);
    });
  }

  public addFileSystemStormListener(callback: (data: any[], objectThis: any) => any, objectThis: any): void {
    this.hubConnection.on('fileSystemStorm', (data: any[]) => {
      console.log(`⚡ [SignalR] fileSystemStorm: ${data?.length || 0} changes after storm`);
      callback(data, objectThis);
    });
  }

}
