<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageOutputPath Condition="$([MSBuild]::IsOSPlatform('Windows'))">C:\sviluppo\AdToolsPackages</PackageOutputPath>
    <PackageOutputPath Condition="!$([MSBuild]::IsOSPlatform('Windows'))">bin/Packages</PackageOutputPath>
    <Version>3.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentNHibernate" Version="3.1.0" />
  </ItemGroup>

</Project>
