
```plantuml
@startuml

skinparam titleFontSize 30
skinparam titleFontColor blue


title
__title__
end title
 
actor user as u

box "<img:./assets/MdExplorer.png{scale=.4}>\nMdExplorer" #LightBlue
participant "<img:./assets/angular.png{scale=.5}>\nclient" as c
participant "<img:./assets/java.png>\nService" as sc
database "[[#schema schema]]" as edb

end box
participant "<img:./assets/filesystem.png{scale=.7}>\nfilesystem" as fs


legend 
Legenda
<img:./assets/rest.png{scale=.5}> request/response REST
<img:./assets/signalR.png{scale=.5}> signalR event
<img:./assets/event.png{scale=.5}>  Event
end legend

u->c
note over u
{{
salt
{+
<b>Store data 
[save]
}
}}
end note
c->sc:request \n(post)<img:../../assets/rest.png{scale=.5}>
sc->edb: store data
note over edb
table 1
end note
sc-->c: response
c-->u
note over u
{{
salt
{+
<b>Done! 
}
}}
end note
@enduml
```

# Schema

## Table 1

||Field| Description|
||:--|:--|
|:key:|id| key|
