using System;
using System.Collections.Generic;

namespace MdExplorer.Abstractions.Entities.UserDB
{
    /// <summary>
    /// Represents Git credentials that can be shared across multiple repositories.
    /// This enables single-point credential management where one set of credentials
    /// can be used by many repositories.
    /// </summary>
    public class GitCredential
    {
        /// <summary>
        /// Unique identifier for this credential set
        /// </summary>
        public virtual Guid Id { get; set; }

        /// <summary>
        /// Friendly name for this credential (e.g., "Personal GitHub", "Work GitLab")
        /// </summary>
        public virtual string AccountName { get; set; }

        /// <summary>
        /// Type of Git hosting service: GitHub, GitLab, Bitbucket, Generic
        /// </summary>
        public virtual string AccountType { get; set; }

        /// <summary>
        /// Username for authentication (separate from commit username)
        /// </summary>
        public virtual string AuthUsername { get; set; }

        /// <summary>
        /// GitHub Personal Access Token (PAT) for HTTPS authentication
        /// </summary>
        public virtual string GitHubPAT { get; set; }

        /// <summary>
        /// GitLab Personal Access Token for HTTPS authentication
        /// </summary>
        public virtual string GitLabToken { get; set; }

        /// <summary>
        /// Path to SSH private key for SSH authentication
        /// </summary>
        public virtual string SSHKeyPath { get; set; }

        /// <summary>
        /// Bitbucket App Password for HTTPS authentication
        /// </summary>
        public virtual string BitbucketAppPassword { get; set; }

        /// <summary>
        /// Password for HTTPS authentication (for username/password method)
        /// </summary>
        public virtual string HttpsPassword { get; set; }

        /// <summary>
        /// Whether this credential is currently active/enabled
        /// </summary>
        public virtual bool IsActive { get; set; }

        /// <summary>
        /// Timestamp when this credential was created
        /// </summary>
        public virtual DateTime CreatedAt { get; set; }

        /// <summary>
        /// Timestamp when this credential was last updated
        /// </summary>
        public virtual DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Repositories using this credential (navigation property)
        /// </summary>
        public virtual IList<GitRepositoryAccount> Repositories { get; set; }

        public GitCredential()
        {
            // Id is auto-generated by NHibernate via GuidComb strategy
            IsActive = true;
            CreatedAt = DateTime.UtcNow;
            UpdatedAt = DateTime.UtcNow;
            Repositories = new List<GitRepositoryAccount>();
        }
    }
}
