using System;

namespace MdExplorer.Abstractions.Entities.UserDB
{
    /// <summary>
    /// Represents Git configuration for a specific repository.
    /// Links a repository to shared credentials and stores repository-specific settings.
    /// </summary>
    public class GitRepositoryAccount
    {
        /// <summary>
        /// Unique identifier for this repository configuration
        /// </summary>
        public virtual Guid Id { get; set; }

        /// <summary>
        /// Absolute path to the Git repository this configuration is associated with.
        /// This is the primary key for repository-specific settings.
        /// </summary>
        public virtual string RepositoryPath { get; set; }

        /// <summary>
        /// Foreign key to the shared credential used by this repository.
        /// Nullable to support gradual migration.
        /// </summary>
        public virtual Guid? CredentialId { get; set; }

        /// <summary>
        /// Navigation property to the shared credential.
        /// </summary>
        public virtual GitCredential Credential { get; set; }

        /// <summary>
        /// Preferred authentication method for this repository: "token", "username_password", "ssh".
        /// If null or "auto", the system will try to detect the best method.
        /// </summary>
        public virtual string PreferredAuthMethod { get; set; }

        /// <summary>
        /// Git username for commits (git config user.name)
        /// </summary>
        public virtual string Username { get; set; }

        /// <summary>
        /// Git email for commits (git config user.email)
        /// </summary>
        public virtual string Email { get; set; }

        /// <summary>
        /// Optional user notes about this repository configuration
        /// </summary>
        public virtual string Notes { get; set; }

        /// <summary>
        /// Whether this configuration is currently active/enabled
        /// </summary>
        public virtual bool IsActive { get; set; }

        /// <summary>
        /// Timestamp when this configuration was created
        /// </summary>
        public virtual DateTime CreatedAt { get; set; }

        /// <summary>
        /// Timestamp when this configuration was last updated
        /// </summary>
        public virtual DateTime UpdatedAt { get; set; }

        public GitRepositoryAccount()
        {
            // Id is auto-generated by NHibernate via GuidComb strategy
            // DO NOT set Id here - it confuses NHibernate into thinking this is an existing entity
            IsActive = true;
            CreatedAt = DateTime.UtcNow;
            UpdatedAt = DateTime.UtcNow;
        }

        #region Convenience Properties (read from Credential)

        /// <summary>
        /// Gets the account name from the linked credential
        /// </summary>
        public virtual string AccountName => Credential?.AccountName;

        /// <summary>
        /// Gets the account type from the linked credential
        /// </summary>
        public virtual string AccountType => Credential?.AccountType;

        /// <summary>
        /// Gets the auth username from the linked credential
        /// </summary>
        public virtual string AuthUsername => Credential?.AuthUsername;

        /// <summary>
        /// Gets the GitHub PAT from the linked credential
        /// </summary>
        public virtual string GitHubPAT => Credential?.GitHubPAT;

        /// <summary>
        /// Gets the GitLab token from the linked credential
        /// </summary>
        public virtual string GitLabToken => Credential?.GitLabToken;

        /// <summary>
        /// Gets the SSH key path from the linked credential
        /// </summary>
        public virtual string SSHKeyPath => Credential?.SSHKeyPath;

        /// <summary>
        /// Gets the Bitbucket app password from the linked credential
        /// </summary>
        public virtual string BitbucketAppPassword => Credential?.BitbucketAppPassword;

        /// <summary>
        /// Gets the HTTPS password from the linked credential
        /// </summary>
        public virtual string HttpsPassword => Credential?.HttpsPassword;

        #endregion
    }
}
