using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using Markdig;
using Markdig.Extensions.Tables;
using Markdig.Extensions.Yaml;
using Markdig.Renderers.Html;
using Markdig.Syntax;
using Microsoft.Extensions.Logging;

namespace MdExplorer.Features.Services.SourceMapping
{
    /// <summary>
    /// Renders markdown to HTML decorating each block with data-mde-line-start / data-mde-line-end
    /// attributes holding 1-based line numbers of the ORIGINAL file on disk.
    ///
    /// The markdown handed to Markdig is not the file content: it has been rewritten by the
    /// pre-conversion commands (emoji→png, plantuml→svg, link rewrites, ...), which can add or
    /// remove lines. Markdig spans therefore refer to the transformed text; a line-based diff
    /// (Myers) between original and transformed text translates them back to file lines.
    ///
    /// Blocks whose lines are entirely generated by the transforms get NO attributes: the
    /// selection feature simply won't offer itself there. Wrong line numbers are never emitted.
    /// </summary>
    public class MarkdownSourceMapService
    {
        // Above this size the mapping is skipped and the caller gets a legacy render:
        // the AI-selection feature degrades (no attributes), the document still renders.
        public const int MaxLines = 20000;

        // Myers diff distance cap. Transforms touch few lines, so the real D is small;
        // this bounds memory (trace ≈ D² ints) on pathological inputs.
        private const int MaxDiffDistance = 2000;

        private readonly ILogger<MarkdownSourceMapService> _logger;

        public MarkdownSourceMapService(ILogger<MarkdownSourceMapService> logger)
        {
            _logger = logger;
        }

        public string RenderHtmlWithSourceMap(string originalText, string transformedText, MarkdownPipeline pipeline)
        {
            var originalLines = SplitLines(originalText);
            var transformedLines = SplitLines(transformedText);

            if (originalLines.Length > MaxLines || transformedLines.Length > MaxLines)
            {
                _logger.LogWarning(
                    "[SourceMap] Document too large ({OriginalLines}/{TransformedLines} lines, cap {MaxLines}): rendering without source map, AI selection disabled for this document",
                    originalLines.Length, transformedLines.Length, MaxLines);
                return Markdown.ToHtml(transformedText, pipeline);
            }

            var map = BuildLineMap(originalLines, transformedLines);

            var document = Markdown.Parse(transformedText, pipeline);
            var lineStartOffsets = BuildLineStartOffsets(transformedText);

            foreach (var block in document.Descendants().OfType<Block>())
            {
                DecorateBlock(block, map, lineStartOffsets, transformedLines.Length);
            }

            return Markdown.ToHtml(document, pipeline);
        }

        private void DecorateBlock(Block block, int[] map, int[] lineStartOffsets, int transformedLineCount)
        {
            if (!ShouldDecorate(block))
            {
                return;
            }

            var startLine = block.Line;
            if (startLine < 0 || startLine >= transformedLineCount)
            {
                return;
            }

            var endLine = block.Span.IsEmpty
                ? startLine
                : OffsetToLine(lineStartOffsets, block.Span.End);
            if (endLine < startLine)
            {
                endLine = startLine;
            }
            if (endLine >= transformedLineCount)
            {
                endLine = transformedLineCount - 1;
            }

            // Shrink inwards past lines generated by the pre-conversion transforms.
            var originalStart = -1;
            for (var i = startLine; i <= endLine; i++)
            {
                if (map[i] >= 0) { originalStart = map[i]; break; }
            }
            var originalEnd = -1;
            for (var i = endLine; i >= startLine; i--)
            {
                if (map[i] >= 0) { originalEnd = map[i]; break; }
            }

            if (originalStart < 0 || originalEnd < originalStart)
            {
                // Entirely generated content (e.g. plantuml svg link): no attributes.
                return;
            }

            var attributes = block.GetAttributes();
            attributes.AddProperty("data-mde-line-start", (originalStart + 1).ToString());
            attributes.AddProperty("data-mde-line-end", (originalEnd + 1).ToString());
        }

        private static bool ShouldDecorate(Block block)
        {
            switch (block)
            {
                case YamlFrontMatterBlock _:
                    return false;
                case HeadingBlock _:
                case ParagraphBlock _:
                case ListBlock _:
                case ListItemBlock _:
                case QuoteBlock _:
                case CodeBlock _: // includes FencedCodeBlock
                case Table _:
                case ThematicBreakBlock _:
                    return true;
                default:
                    return false;
            }
        }

        internal static string[] SplitLines(string text)
        {
            var lines = text.Split('\n');
            for (var i = 0; i < lines.Length; i++)
            {
                var line = lines[i];
                if (line.Length > 0 && line[line.Length - 1] == '\r')
                {
                    lines[i] = line.Substring(0, line.Length - 1);
                }
            }
            return lines;
        }

        private static int[] BuildLineStartOffsets(string text)
        {
            var starts = new List<int> { 0 };
            for (var i = 0; i < text.Length; i++)
            {
                if (text[i] == '\n')
                {
                    starts.Add(i + 1);
                }
            }
            return starts.ToArray();
        }

        private static int OffsetToLine(int[] lineStartOffsets, int offset)
        {
            var index = Array.BinarySearch(lineStartOffsets, offset);
            return index >= 0 ? index : ~index - 1;
        }

        /// <summary>
        /// Line map transformed→original: result[j] = 0-based line index in the original text,
        /// or -1 when line j of the transformed text was generated by the transforms.
        /// Myers greedy diff on lines, with common prefix/suffix trimming.
        /// </summary>
        internal int[] BuildLineMap(string[] originalLines, string[] transformedLines)
        {
            var n = originalLines.Length;
            var m = transformedLines.Length;
            var map = new int[m];
            for (var j = 0; j < m; j++) map[j] = -1;

            var prefix = 0;
            while (prefix < n && prefix < m && originalLines[prefix] == transformedLines[prefix])
            {
                map[prefix] = prefix;
                prefix++;
            }
            var suffix = 0;
            while (suffix < n - prefix && suffix < m - prefix
                   && originalLines[n - 1 - suffix] == transformedLines[m - 1 - suffix])
            {
                map[m - 1 - suffix] = n - 1 - suffix;
                suffix++;
            }

            var an = n - prefix - suffix;
            var bm = m - prefix - suffix;
            if (an == 0 || bm == 0)
            {
                return map;
            }

            var matched = MyersMatch(originalLines, prefix, an, transformedLines, prefix, bm);
            if (matched == null)
            {
                _logger.LogWarning(
                    "[SourceMap] Diff distance exceeded {MaxDiffDistance}: {UnmappedLines} middle lines left unmapped, AI selection disabled on the affected blocks",
                    MaxDiffDistance, bm);
                return map;
            }

            foreach (var pair in matched)
            {
                map[pair.Value] = pair.Key; // Key = original index, Value = transformed index
            }
            PairStandaloneImages(map, originalLines, transformedLines);
            PairModifiedRuns(map, n);
            return map;
        }

        // An image alone on its line, as ToolbarImagesHtml finds it: plain or with {attributes}.
        private static readonly Regex StandaloneImageLine = new Regex(@"^!\[([^\]]*)\]\(([^)]+)\)(\{[^}]*\})?[ \t]*$", RegexOptions.Compiled);
        private static readonly Regex ImageAtLineStart = new Regex(@"^!\[([^\]]*)\]\(([^)]+)\)", RegexOptions.Compiled);

        /// <summary>
        /// Whether a transformed image line shows the file's image. Same alt text, and the file's
        /// path inside the transformed one: ManageLinkAbsolutePath rewrites <c>/assets/a.png</c> as
        /// <c>/api/mdexplorer/assets/a.png?connectionId=…</c> (the fragment after the query).
        /// </summary>
        private static bool SameImage(Match original, Match transformed)
        {
            var path = original.Groups[2].Value;
            var hash = path.IndexOf('#');
            if (hash >= 0) path = path.Substring(0, hash);
            return original.Groups[1].Value == transformed.Groups[1].Value
                && transformed.Groups[2].Value.Contains(path);
        }

        /// <summary>
        /// Images. <c>ToolbarImagesHtml</c> turns one image line into an HTML block of about ten
        /// lines, blank lines included, and the diff pairs the file's blank lines with those blank
        /// lines inside the block, at random (measured 10/09/2026): the image line never gets a
        /// number, so an image could not be selected, nor used as the place to paste another one.
        ///
        /// <para>
        /// The image itself survives at the start of one transformed line, <c>![alt](path){…}</c>,
        /// with the same alt text and its path perhaps rewritten (<see cref="SameImage"/>). Between
        /// two non-blank lines the diff matched exactly, when the file
        /// holds nothing but blank lines and images standing alone (column 0, a blank line or the
        /// edge of the file above and below), and the transformed text shows the same images in
        /// the same order, each image line is paired with its own. Anything else in between — an
        /// image in a sentence, two images on consecutive lines, any other line — leaves the
        /// stretch as it was: unmapped, never guessed.
        /// </para>
        ///
        /// <para>
        /// Inside a stretch that is paired, the blank lines the diff matched are unpaired: they
        /// belong to the HTML around the images, and keeping them would make the map go backwards.
        /// Runs before <see cref="PairModifiedRuns"/>, which positionally paired a line of that HTML
        /// with the next line of the file when the lengths happened to agree.
        /// </para>
        /// </summary>
        private static void PairStandaloneImages(int[] map, string[] originalLines, string[] transformedLines)
        {
            var transformedOf = new int[originalLines.Length];
            for (var i = 0; i < transformedOf.Length; i++) transformedOf[i] = -1;
            for (var j = 0; j < map.Length; j++)
            {
                if (map[j] >= 0) transformedOf[map[j]] = j;
            }

            var previousAnchor = -1;
            for (var i = 0; i <= originalLines.Length; i++)
            {
                var isAnchor = i == originalLines.Length
                    || (transformedOf[i] >= 0 && !string.IsNullOrWhiteSpace(originalLines[i]));
                if (!isAnchor)
                {
                    continue;
                }
                PairImagesBetween(map, originalLines, transformedLines, transformedOf, previousAnchor, i);
                previousAnchor = i;
            }
        }

        /// <param name="first">Original index of the anchor before the stretch, or -1.</param>
        /// <param name="last">Original index of the anchor after the stretch, or the line count.</param>
        private static void PairImagesBetween(int[] map, string[] originalLines, string[] transformedLines, int[] transformedOf, int first, int last)
        {
            var images = new List<KeyValuePair<int, Match>>();
            for (var i = first + 1; i < last; i++)
            {
                if (string.IsNullOrWhiteSpace(originalLines[i]))
                {
                    continue;
                }
                var match = StandaloneImageLine.Match(originalLines[i]);
                var blankAbove = i == 0 || string.IsNullOrWhiteSpace(originalLines[i - 1]);
                var blankBelow = i == originalLines.Length - 1 || string.IsNullOrWhiteSpace(originalLines[i + 1]);
                if (!match.Success || !blankAbove || !blankBelow)
                {
                    return;
                }
                images.Add(new KeyValuePair<int, Match>(i, match));
            }
            if (images.Count == 0)
            {
                return;
            }

            var from = first < 0 ? 0 : transformedOf[first] + 1;
            var to = last >= originalLines.Length ? transformedLines.Length : transformedOf[last];
            var rendered = new List<int>();
            for (var j = from; j < to; j++)
            {
                if (ImageAtLineStart.IsMatch(transformedLines[j])) rendered.Add(j);
            }
            if (rendered.Count != images.Count)
            {
                return;
            }
            for (var k = 0; k < images.Count; k++)
            {
                if (!SameImage(images[k].Value, ImageAtLineStart.Match(transformedLines[rendered[k]])))
                {
                    return;
                }
            }

            for (var j = from; j < to; j++)
            {
                map[j] = -1;
            }
            for (var k = 0; k < images.Count; k++)
            {
                map[rendered[k]] = images[k].Key;
            }
        }

        /// <summary>
        /// A transform that rewrites a line in place (emoji→png, link rewrite, numbering)
        /// shows up in the diff as an equal-length delete+insert run. Pair those runs
        /// positionally, like diff tools do for "changed" lines. Runs of different length
        /// (e.g. plantuml block → single image line) stay unmapped: pairing them could
        /// produce a replace range that cuts a source block in half.
        /// </summary>
        private static void PairModifiedRuns(int[] map, int originalLineCount)
        {
            var originalCursor = 0;
            var j = 0;
            var m = map.Length;
            while (j < m)
            {
                if (map[j] >= 0)
                {
                    originalCursor = map[j] + 1;
                    j++;
                    continue;
                }
                var runStart = j;
                while (j < m && map[j] < 0)
                {
                    j++;
                }
                var originalRunEnd = j < m ? map[j] : originalLineCount;
                if (originalRunEnd - originalCursor == j - runStart)
                {
                    for (var t = 0; t < j - runStart; t++)
                    {
                        map[runStart + t] = originalCursor + t;
                    }
                }
                originalCursor = originalRunEnd;
            }
        }

        /// <summary>
        /// Myers greedy shortest-edit diff over a[aStart..aStart+aLen) vs b[bStart..bStart+bLen).
        /// Returns matched (originalIndex, transformedIndex) pairs, or null when the edit
        /// distance exceeds <see cref="MaxDiffDistance"/>.
        /// </summary>
        private static List<KeyValuePair<int, int>> MyersMatch(
            string[] a, int aStart, int aLen,
            string[] b, int bStart, int bLen)
        {
            var maxD = Math.Min(aLen + bLen, MaxDiffDistance);
            var offset = maxD;
            var v = new int[2 * maxD + 2];
            var trace = new List<int[]>();

            var foundD = -1;
            for (var d = 0; d <= maxD; d++)
            {
                // Snapshot of the k∈[-d..d] window, as left by depth d-1.
                var snapshot = new int[2 * d + 1];
                Array.Copy(v, offset - d, snapshot, 0, 2 * d + 1);
                trace.Add(snapshot);

                for (var k = -d; k <= d; k += 2)
                {
                    int x;
                    if (k == -d || (k != d && v[offset + k - 1] < v[offset + k + 1]))
                    {
                        x = v[offset + k + 1];
                    }
                    else
                    {
                        x = v[offset + k - 1] + 1;
                    }
                    var y = x - k;
                    while (x < aLen && y < bLen && a[aStart + x] == b[bStart + y])
                    {
                        x++;
                        y++;
                    }
                    v[offset + k] = x;
                    if (x >= aLen && y >= bLen)
                    {
                        foundD = d;
                        break;
                    }
                }
                if (foundD >= 0)
                {
                    break;
                }
            }

            if (foundD < 0)
            {
                return null;
            }

            var matches = new List<KeyValuePair<int, int>>();
            var cx = aLen;
            var cy = bLen;
            for (var d = foundD; d > 0 && (cx > 0 || cy > 0); d--)
            {
                var snapshot = trace[d];
                var snapshotOffset = d;
                var k = cx - cy;
                int prevK;
                if (k == -d || (k != d && snapshot[snapshotOffset + k - 1] < snapshot[snapshotOffset + k + 1]))
                {
                    prevK = k + 1;
                }
                else
                {
                    prevK = k - 1;
                }
                var prevX = snapshot[snapshotOffset + prevK];
                var prevY = prevX - prevK;
                while (cx > prevX && cy > prevY)
                {
                    cx--;
                    cy--;
                    matches.Add(new KeyValuePair<int, int>(aStart + cx, bStart + cy));
                }
                cx = prevX;
                cy = prevY;
            }
            while (cx > 0 && cy > 0)
            {
                cx--;
                cy--;
                matches.Add(new KeyValuePair<int, int>(aStart + cx, bStart + cy));
            }
            return matches;
        }
    }
}
